code_hash = {"Curaçao"=>["cw", "ang"], "Timor-Leste"=>["tl", "usd"], "France"=>["fr", "eur"], "United States"=>["us", "usd"], "Mauritania"=>["mr", "mro"], 
  "Heard Island and McDonald Islands"=>["hm", "aud"], "Sweden"=>["se", "sek"], "Tokelau"=>["tk", "nzd"], "Montserrat"=>["ms", "xcd"], "Central African Republic"=>["cf", "xaf"], 
  "Yemen"=>["ye", "yer"], "Guatemala"=>["gt", "gtq"], "Kuwait"=>["kw", "kwd"], "Uruguay"=>["uy", "uyu"], "Ecuador"=>["ec", "ecs"], "Hungary"=>["hu", "huf"], "Poland"=>["pl", "pln"], 
  "Turkmenistan"=>["tm", "tmt"], "Turkey"=>["tr", "try"], "Tunisia"=>["tn", "tnd"], "Tajikistan"=>["tj", "tjs"], "Niue"=>["nu", "nzd"], "Burkina Faso"=>["bf", "xof"], 
  "Belarus"=>["by", "byr"], "Bangladesh"=>["bd", "bdt"], "Barbados"=>["bb", "bbd"], "Antarctica"=>["aq", "aqd"], "Uzbekistan"=>["uz", "uzs"], "Bolivia"=>["bo", "bob"], 
  "Pitcairn Islands"=>["pn", "nzd"], "Chad"=>["td", "xaf"], "Spain"=>["es", "eur"], "Marshall Islands"=>["mh", "usd"], "Netherlands"=>["nl", "eur"], "Bouvet Island"=>["bv", "nok"], 
  "Antigua and Barbuda"=>["ag", "xcd"], "French Guiana"=>["gf", "eur"], "Gabon"=>["ga", "xaf"], "Syria"=>["sy", "syp"], "Libya"=>["ly", "lyd"], "Albania"=>["al", "all"], 
  "Palau"=>["pw", "usd"], "Philippines"=>["ph", "php"], "Kenya"=>["ke", "kes"], "Eritrea"=>["er", "etb"], "Kiribati"=>["ki", "aud"], "Western Sahara"=>["eh", "mad"], 
  "Egypt"=>["eg", "egp"], "Swaziland"=>["sz", "szl"], "Guadeloupe"=>["gp", "eur"], "Armenia"=>["am", "amd"], "Oman"=>["om", "omr"], "Costa Rica"=>["cr", "crc"], "Samoa"=>["ws", "eur"], 
  "Caribbean Netherlands"=>["bq", "usd"], "Honduras"=>["hn", "hnl"], "Argentina"=>["ar", "ars"], "Grenada"=>["gd", "xcd"], "El Salvador"=>["sv", "svc"], "Chile"=>["cl", "clp"], 
  "Lebanon"=>["lb", "lbp"], "Palestine"=>["ps", "jod"], "Nauru"=>["nr", "aud"], "Ireland"=>["ie", "eur"], "Liberia"=>["lr", "lrd"], "Saint Barthelemy"=>["bl", "eur"], 
  "Comoros"=>["km", "kmf"], "Country"=>["countrycode", "currencycode"], "Transnistria"=>["mda", "rub"], "Iraq"=>["iq", "iqd"], "Portugal"=>["pt", "eur"], 
  "Åland Islands"=>["ax", "eur"], "Zimbabwe"=>["zw", "zwd"], "Mongolia"=>["mn", "mnt"], "Saint Kitts and Nevis"=>["kn", "xcd"], "Saint Lucia"=>["lc", "xcd"], "Macau"=>["mo", "mop"], 
  "Bahrain"=>["bh", "bhd"], "Hong Kong"=>["hk", "hkd"], "Cook Islands"=>["ck", "nzd"], "India"=>["in", "inr"], "Slovakia"=>["sk", "skk"], "Bulgaria"=>["bg", "bgn"], 
  "Tanzania"=>["tz", "tzs"], "Solomon Islands"=>["sb", "sbd"], "Nepal"=>["np", "npr"], "Belgium"=>["be", "eur"], "Nicaragua"=>["ni", "nio"], "Réunion"=>["re", "eur"], 
  "Liechtenstein"=>["li", "chf"], "Svalbard and Jan Mayen"=>["sj", "nok"], "Saint Martin"=>["mf", "ang"], "Georgia"=>["ge", "gel"], "Ceuta and Melilla"=>["es", "eur"], 
  "Venezuela"=>["ve", "vef"], "Morocco"=>["ma", "mad"], "Haiti"=>["ht", "htg"], "Mauritius"=>["mu", "mur"], "Ascension Island"=>["ac", "gbp"], "Germany"=>["de", "eur"], 
  "Kyrgyzstan"=>["kg", "kgs"], "Jersey"=>["je", "gbp"], "Cambodia"=>["kh", "khr"], "Saint Helena"=>["sh", "gbp"], "Puerto Rico"=>["pr", "usd"], "Seychelles"=>["sc", "scr"], 
  "Greenland"=>["gl", "dkk"], "Andorra"=>["ad", "eur"], "Switzerland"=>["ch", "chf"], "Canary Islands"=>["ic", "eur"], "American Samoa"=>["as", "eur"], "Mozambique"=>["mz", "mzn"], 
  "Italy"=>["it", "eur"], "Wallis and Futuna"=>["wf", "xpf"], "U.S. Outlying Islands"=>["um", "usd"], "Moldova"=>["md", "mdl"], "Madagascar"=>["mg", "mga"], 
  "Cyprus"=>["cy", "cyp"], "Colombia"=>["co", "cop"], "Ghana"=>["gh", "ghs"], "Tristan da Cunha"=>["sh", "gbp"], "Greece"=>["gr", "eur"], "Sierra Leone"=>["sl", "sll"], 
  "Finland"=>["fi", "eur"], "South Africa"=>["za", "zar"], "Djibouti"=>["dj", "djf"], "Brunei"=>["bn", "bnd"], "Uganda"=>["ug", "ugx"], "Lithuania"=>["lt", "ltl"], 
  "Benin"=>["bj", "xof"], "United Arab Emirates"=>["ae", "aed"], "Botswana"=>["bw", "bwp"], "Jamaica"=>["jm", "jmd"], "Suriname"=>["sr", "srd"], "Guyana"=>["gy", "gyd"], 
  "Bermuda"=>["bm", "bmd"], "Saint Vincent and the Grenadines"=>["vc", "xcd"], "Cuba"=>["cu", "cup"], "Luxembourg"=>["lu", "eur"], "São Tomé and Príncipe"=>["st", "std"], 
  "Cape Verde"=>["cv", "cve"], "Cocos Islands"=>["cc", "aud"], "Anguilla"=>["ai", "xcd"], "Clipperton Island"=>["cp", "eur"], "Algeria"=>["dz", "dzd"], 
  "Christmas Island"=>["cx", "aud"], "Martinique"=>["mq", "eur"], "Jordan"=>["jo", "jod"], "Nigeria"=>["ng", "ngn"], "Ethiopia"=>["et", "etb"], "Taiwan"=>["tw", "twd"], 
  "Micronesia"=>["fm", "usd"], "Equatorial Guinea"=>["gq", "xaf"], "Thailand"=>["th", "thb"], "Dominica"=>["dm", "xcd"], "North Korea"=>["kp", "kpw"], "Diego Garcia"=>["dg", "gbp"], 
  "Russia"=>["ru", "rub"], "New Zealand"=>["nz", "nzd"], "Norway"=>["no", "nok"], "Kosovo"=>["xk", "eur"], "Sudan"=>["sd", "sdg"], "Peru"=>["pe", "pen"], "Namibia"=>["na", "nad"], 
  "Papua New Guinea"=>["pg", "pgk"], "Tonga"=>["to", "top"], "Lesotho"=>["ls", "lsl"], "Iceland"=>["is", "isk"], "United Kingdom"=>["gb", "gbp"], "Angola"=>["ao", "aoa"], 
  "Gibraltar"=>["gi", "gip"], "British Indian Ocean Territory"=>["io", "usd"], "Malta"=>["mt", "mtl"], "Romania"=>["ro", "ron"], "Cayman Islands"=>["ky", "kyd"], 
  "Sint Maarten"=>["sxm", "ang"], "Nagorno-Karabakh"=>["az", "azn"], "Tuvalu"=>["tv", "aud"], "Trinidad and Tobago"=>["tt", "ttd"], "Saint Pierre and Miquelon"=>["pm", "eur"], 
  "Mexico"=>["mx", "mxn"], "Serbia"=>["rs", "rsd"], "Singapore"=>["sg", "sgd"], "Vatican City"=>["va", "eur"], "Kazakhstan"=>["kz", "kzt"], "Afghanistan"=>["af", "afn"], 
  "Malawi"=>["mw", "mwk"], "Bosnia and Herzegovina"=>["ba", "bam"], "Monaco"=>["mc", "eur"], "South Georgia and the South Sandwich Islands"=>["gs", "gbp"], 
  "Dominican Republic"=>["do", "dop"], "Congo-DRC"=>["cd", "cdf"], "Estonia"=>["ee", "eek"], "Fiji"=>["fj", "fjd"], "Rwanda"=>["rw", "rwf"], "Malaysia"=>["my", "myr"], 
  "Denmark"=>["dk", "dkk"], "Sri Lanka"=>["lk", "lkr"], "Faroe Islands"=>["fo", "dkk"], "Bahamas"=>["bs", "bsd"], "Zambia"=>["zm", "zmk"], "Turks and Caicos Islands"=>["tc", "usd"], 
  "Isle of Man"=>["im", "gbp"], "Falkland Islands"=>["fk", "fkp"], "Laos"=>["la", "lak"], "Côte d’Ivoire"=>["ci", "xof"], "Guinea"=>["gn", "gnf"], "Aruba"=>["aw", "ang"], 
  "Croatia"=>["hr", "hrk"], "Gambia"=>["gm", "gmd"], "Australia"=>["au", "aud"], "New Caledonia"=>["nc", "xpf"], "Slovenia"=>["si", "eur"], "Montenegro"=>["me", "eur"], 
  "Senegal"=>["sn", "xof"], "Vietnam"=>["vn", "vnd"], "Macedonia"=>["mk", "mkd"], "Congo-Republic"=>["cg", "xaf"], "Guinea-Bissau"=>["gw", "xof"], "Cameroon"=>["cm", "xaf"], 
  "French Southern Territories"=>["tf", "eur"], "Pakistan"=>["pk", "pkr"], "Japan"=>["jp", "jpy"], "Myanmar"=>["mm", "mmk"], "French Polynesia"=>["pf", "xpf"], 
  "San Marino"=>["sm", "eur"], "Belize"=>["bz", "bzd"], "Canada"=>["ca", "cad"], "South Sudan"=>["ss", "ssp"], "U.S. Virgin Islands"=>["vi", "usd"], 
  "Qatar"=>["qa", "qar"], "Guam"=>["gu", "usd"], "Vanuatu"=>["vu", "vuv"], "Northern Mariana Islands"=>["mp", "usd"], "South Korea"=>["kr", "krw"], "Austria"=>["at", "eur"], 
  "Latvia"=>["lv", "lvl"], "Paraguay"=>["py", "pyg"], "Bhutan"=>["bt", "inr"], "British Virgin Islands"=>["vg", "usd"], "Ukraine"=>["ua", "uah"], "Saudi Arabia"=>["sa", "sar"], 
  "Mayotte"=>["yt", "eur"], "China"=>["cn", "cny"], "Brazil"=>["br", "brl"], "Norfolk Island"=>["nf", "aud"], "Togo"=>["tg", "xof"], "Maldives"=>["mv", "mvr"], "Israel"=>["il", "ils"], 
  "Panama"=>["pa", "pab"], "Niger"=>["ne", "xof"], "Guernsey"=>["gg", "ggp"], "Iran"=>["ir", "irr"], "Burundi"=>["bi", "bif"], "Somalia"=>["so", "sos"], "Indonesia"=>["id", "idr"], 
  "Azerbaijan"=>["az", "azn"], "Mali"=>["ml", "xof"], "Czech Republic"=>["cz", "czk"]}
Country.all.each do |country|
  cc_record = code_hash[country.name]
  if cc_record.present?
    country.update_attributes(:code => cc_record[0], :currency_code=> cc_record[1])
  end
end